# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20181112_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerisk',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
